// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdixiznvjjaerbrhdifu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkaXhpem52amphZXJicmhkaWZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjE2MzAsImV4cCI6MjA2NTQ5NzYzMH0.KaBKbhu_VlQ2kuooTaVbkdPLFxgjQYqzzfZZxAR0nWM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);